version: '3.3'
services:
  mygarden:
    image: tomcat:9
    ports:
      - "8080:8080"
      - "9000:8000"
    environment:
      JPDA_ADDRESS: "*:8000"
      JPDA_TRANSPORT: dt_socket
    depends_on:
      - "mygarden-mysql"
    volumes:
      - ./target/mygarden-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    container_name: mygarden
    command: "bash  /usr/local/tomcat/bin/catalina.sh jpda run"

  mygarden-mysql:
    image: "mysql"
    ports :
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: mygarden-mysql

networks:
  default:
    name: amt-aws