version: '3.3'
services:
  mygarden:
    image: tomcat:9
    ports:
      - "8080:8080"
      - "9000:8000"
    environment:
      JPDA_ADDRESS: "*:8000"
      JPDA_TRANSPORT: dt_socket
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - "mygarden-mysql"
    volumes:
      - ./target/mygarden-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ./wait-for-it.sh:/usr/local/wait-for-it.sh
    container_name: mygarden
    entrypoint: ["/usr/local/wait-for-it.sh","-t","0","mygarden-mysql.amt-aws:3306","--","/usr/local/tomcat/bin/catalina.sh", "jpda","run"  ]
    command: ""

  mygarden-mysql:
    image: "mysql"
    ports :
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: mygarden-mysql

networks:
  default:
    name: amt-aws
