@startuml
'https://plantuml.com/class-diagram

class Fruit <<entity>>{
-String name
-float price
-int quantity
-Set<Category> categories
-String image
+Fruit(String name)
-Fruit()
+addCategory(Category c)
+deleteCategory(Category c)
+removeQuantity()
+deleteCategories()
+setCategories(Set<Category> categories)
}
class Item <<entity>>{
-Long id
-String username
-Fruit fruit
-int quantity
+Item(String username, Fruit fruit, int quantity)
-Item()
+addSeveralFruit(int quantity)


}
class Category <<entity>>{
-string name
+Category()
+setFruits(Set<Fruit fruits)
}


Item "*"- "1" Fruit : contains >
Fruit "*"- "*" Category : has >
@enduml