name: deployment
on: push
  # todo: remplcer par la branche master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install DMZ ssh-key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.AMT-DMZ-MYGARDEN}}
          known_hosts: 'placeholder'
      - name: Create tunnel
        run: 'ssh -N -L 2222:10.0.1.16:22 MYGARDEN@16.170.194.237'
      - name: Install server ssh-key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.AMT-MYGARDEN}}
          known_hosts: 'placeholder'
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: 'Deploy to server'
        run: rsync -avz ./pom.xml admin@localhost:./test/