name: deployment
on: push
  # todo: remplacer par la branche master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key of DMZ
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.AMT_DMZ_MYGARDEN}}
          name: id_rsa-dmz
          known_hosts: 'placeholder'
          config: |
            Host dmz
              HostName xxx.xxx.xxx.xxx
              User MYGARDEN
              IdentityFile ~/.ssh/id_rsa-dmz
      - name: Install SSH key of MYGARDEN
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.AMT_MYGARDEN}}
          name: id_rsa-target
          known_hosts: 'placeholder' # will be appended to existing .ssh/known_hosts
          config: |                                         # will be appended to existing .ssh/config
            Host target
              HostName yyy.yyy.yyy.yyy
              User admin
              IdentityFile ~/.ssh/id_rsa-target
              ProxyCommand ssh -W %h:%p dmz
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: 'Deploy to server'
        run: scp ./pom.xml target:./test-scp/